language: node_js
node_js:
  - 10.16.2

os: ocx

jobs:
  include:
  - stage: "Bundler"                # naming the Tests stage
    name: "Webpack"    
    script:
      - npm run build
  - stage: deploy
    name: "Deploy to GCP"
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master